export enum Nationality  {
    ALL = 'au,br,ca,ch,de,dk,es,fi,fr,gb,ie,ir,no,nl,nz,tr,us',
    AU = 'au',
    BR = 'br',
    CA = 'ca',
    CH = 'ch',
    DE = 'de',
    DK = 'dk',
    ES = 'es',
    FI = 'fi',
    FR = 'fr',
    GB = 'gb',
    IE = 'ie',
    IR = 'ir',
    NO = 'no',
    NL = 'nl',
    NZ = 'nz',
    TR = 'tr',
    US = 'us'
}
